lcms-engine.gemspec
=> Update `bootstrap-sass` gem

.codeclimate.yml, Gemfile, README.md, app/jobs/lcms/engine/material_generate_job.rb, app/services/lcms/engine/embed_equations.rb, app/services/lcms/engine/material_build_service.rb, config/initializers/wicked_pdf.rb, lcms-engine.gemspec, lib/lcms/engine/engine.rb
Adds integration and settings for [Codeship](https://codeship.com) and [Codeclimate](https://codeclimate.com/) CI services
=> Add Codeship and Codeclimate integrations

app/models/lcms/engine/document.rb, app/services/lcms/engine/document_build_service.rb, app/services/lcms/engine/material_build_service.rb
Sync changes from https://github.com/learningtapestry/openscied-lcms/pull/160
=> Sync latest changes from OSE repository

app/assets/stylesheets/lcms/engine/base/_colors.scss
=> Fix CSS colors

app/services/lcms/engine/html_sanitizer.rb, lcms-engine.gemspec, lib/doc_template/tags/base_tag.rb
- Fix post-processing in case raw metadata
- Allow to inline the tag instead of replacing it with placeholder
Refs https://github.com/learningtapestry/openscied-lcms/issues/288
=> Minor improvements

app/forms/lcms/engine/material_form.rb, lib/document_exporter/thumbnail.rb
refs learningtapestry/openscied-lcms#245
=> added after reimport hook for materials

app/services/lcms/engine/google/drive_service.rb, app/services/lcms/engine/google/script_service.rb, lib/document_exporter/gdoc/base.rb
learningtapestry/openscied-lcms#266
openscied-lcms:
=> (openscied-lcms#266) updates for gdoc processing

.rubocop.yml, lib/doc_template/tables/activity.rb, lib/doc_template/tables/agenda.rb, lib/doc_template/tables/base.rb, lib/doc_template/tables/material_metadata.rb, lib/doc_template/tables/metadata.rb, lib/doc_template/tables/section.rb, lib/doc_template/tables/target.rb, lib/lt/lcms/metadata/base_service.rb, lib/lt/lcms/metadata/service.rb
- Refactor Metadata tables inheritance
- Extract common code base into separate `BaseService`
=> Refactor Metadata tables inheritance

README.md
Refs #26 
Additional source directive for Gemfile will be added in a #23
=> (#26) Add setup information to the README

README.md, db/seeds.rb, db/seeds/development/grades.seeds.rb, lib/tasks/lcms/engine_tasks.rake
Refs #33 
Introduce `lcms_engine:seed_data` rake task to load the initial data
=> (#33) Create rake task to pre-fill the database with base data

README.md, app/assets/javascripts/lcms/engine/components/explore-curriculum/ExploreCurriculumItem.js.jsx, app/assets/javascripts/lcms/engine/components/paginate/PaginationListView.js.jsx, app/assets/javascripts/lcms/engine/components/related-instruction/RelatedInstruction.js.jsx, app/helpers/lcms/engine/tags_helper.rb, app/presenters/lcms/engine/resource_presenter.rb, lcms-engine.gemspec, lib/generators/lcms/engine/install/install_generator.rb, lib/lcms/engine/engine.rb
- Add React 16.8.6
- Fix leftovers from extraction from UB project
- Refactoring to get rid off `React.addons.createFragment`
- Refactoring to get rid off `React.addons.CSSTransitionGroup`
- Update README to address critical note about how to mount the engine properly
=> Upgrade react-rails to the latest version

lib/doc_template/template.rb, spec/lib/doc_template/template_spec.rb
Refs https://github.com/learningtapestry/odell-lcms/issues/253, p.2
=> introduced unregister_tag method

Gemfile, app/views/lcms/engine/admin/documents/index.html.erb, app/views/lcms/engine/admin/materials/index.html.erb
Refs https://github.com/learningtapestry/odell-lcms/issues/254, https://github.com/learningtapestry/odell-lcms/issues/275
https://github.com/learningtapestry/lt-google-api/pull/3 should be merged first
=> Fix ReactJS components calls and update `lt-google-api` ref

app/javascript/components/admin/ImportStatus.jsx
Correctly removes interval upon component unmount process.
=> Fix for `ImportStatus` component

README.md, app/controllers/concerns/lcms/engine/location_storable.rb, app/controllers/lcms/engine/admin/admin_controller.rb, app/controllers/lcms/engine/application_controller.rb, app/controllers/lcms/engine/sessions_controller.rb, config/routes.rb, spec/features/users/login_logout_spec.rb
Refs https://github.com/learningtapestry/odell-lcms/issues/256
=> adjusted devise setup

app/controllers/concerns/lcms/engine/nested_reimportable.rb, app/controllers/lcms/engine/admin/batch_reimports_controller.rb, app/controllers/lcms/engine/admin/documents_controller.rb, app/controllers/lcms/engine/admin/materials_controller.rb, app/forms/lcms/engine/document_form.rb, app/jobs/concerns/lcms/engine/nested_resque_job.rb, app/jobs/lcms/engine/document_generate_gdoc_job.rb, app/jobs/lcms/engine/document_generate_pdf_job.rb, app/jobs/lcms/engine/material_generate_gdoc_job.rb, app/jobs/lcms/engine/material_generate_pdf_job.rb, app/services/lcms/engine/document_generator.rb
ref https://github.com/learningtapestry/odell-lcms/pull/303
=> introduced parsing jobs customization + nested jobs concerns

app/controllers/lcms/engine/documents_controller.rb, app/controllers/lcms/engine/materials_controller.rb, app/helpers/admin/documents_helper.rb, app/serializers/lcms/engine/document_material_serializer.rb, app/serializers/lcms/engine/previews_material_serializer.rb, app/serializers/lcms/engine/resource_details_serializer.rb, app/services/lcms/engine/document_generator.rb, app/services/lcms/engine/material_build_service.rb, app/services/lcms/engine/material_preview_generator.rb
ref https://github.com/learningtapestry/odell-lcms/pull/308
=> changed document/material presenters to config ones

.gitignore, package.json, yarn.lock
Refs [security alert](https://github.com/learningtapestry/lcms-engine/network/alert/yarn.lock/serialize-javascript/closed)
Need to wait when [webpack-connected plugin will be updated](https://github.com/webpack-contrib/compression-webpack-plugin/issues/138)
=> Upgrade serialize-javascript NodeJS package

lib/doc_template/tables/base.rb, spec/lib/doc_template/tables/base_spec.rb
Add option to skip sanitization while parsing metadata
=> Update metadata table parsing

app/javascript/components/admin/association-picker/AssociationPickerItem.jsx, app/javascript/components/admin/association-picker/AssociationPickerResults.jsx, app/javascript/components/admin/association-picker/AssociationPickerWindow.jsx, app/javascript/components/admin/picker/pickerWindowWrapper.jsx, app/javascript/components/admin/resource-picker/ResourcePicker.jsx, app/javascript/components/paginate/PaginationBoxView.jsx, app/javascript/components/paginate/PaginationListView.jsx
Uncomment mistakenly commented out imports.
=> Minor JS fixes

yarn.lock
- minimist
- kind-of (partially)
- acorn (partially)
=> Bump JS dependencies

lib/doc_template/document.rb
=> Make squish after parsing optional

yarn.lock
=> Bump websocket-extensions from 0.1.3 to 0.1.4

app/jobs/concerns/lcms/engine/nested_resque_job.rb, lib/resque_job.rb
Remove Redis key deletion after the first call because we will expire in 1 hour
=> Remove unnecessary redis key deletion

CHANGELOG.md, app/exceptions/document_error.rb, app/exceptions/lcms/engine/document_error.rb, app/exceptions/lcms/engine/material_error.rb, app/exceptions/material_error.rb, lib/doc_template/document.rb, lib/doc_template/objects/toc_helpers.rb, lib/doc_template/tags/base_tag.rb, lib/doc_template/tags/block_tag.rb, lib/doc_template/tags/table_tag.rb, lib/lt/lcms/metadata/service.rb, spec/lib/doc_template/tags/page_break_tag_spec.rb, spec/support/shared_examples/content_tag.rb
=> (#22) Move independent Exceptions classes into engine's namespace

Gemfile.lock, lcms-engine.gemspec, lib/doc_template/document.rb, lib/document_exporter/gdoc/base.rb
=> (#176) Wrap call to Google API Script into retry block
