learningtapestry/lcms-engine

README.md
lcms-engine.gemspec
spec/features/admin/users_spec.rb
spec/support/capybara.rb

Webkit has Qt dependency which is tricky to install on different OS. Here we migrate to use Selenium webdriver to be used with headless Google Chrome.
To achieve that one needs to install `chromedriver` manually. How to do that can be found [here](https://sites.google.com/a/chromium.org/chromedriver/getting-started). To install on macOS:
```sh
brew tap homebrew/cask
brew cask install chromedriver
```

Migrate to headless Chrome to be running with Capybara

---

app/services/lcms/engine/html_sanitizer.rb

Fix for sanitizer: correctly handle the situation when there are no styled tables

(openscied-lcms#334) Check&fix reimport with gdoc templates

---

lib/doc_template/document.rb
lib/doc_template/tags/base_tag.rb

Helps in situations when the tag got corrupted with HTML tags inside its declaration. Found with
https://github.com/learningtapestry/openscied-lcms/issues/349

Handle infinite loop for some tags

---

lib/doc_template/tables/base.rb

The table is detected by a special keyword located in the very first cell of the first row. Otherwise, if the keyword is located inside any other table, then such a table will be treated like containing metadata.

Fix metadata table detection

---

lib/lt/lcms/metadata/context.rb
spec/lib/lt/lcms/metadata/context_spec.rb
spec/support/resource_factory_helper.rb

Refs #35 
- Correctly create document inside Curriculum tree
- Introduce separate helpers to `Resource` model to update the resources and their order

(#35) Fix document creation inside Curriculum tree

---

app/controllers/lcms/engine/admin/resource_picker_controller.rb
app/entities/lcms/engine/breadcrumbs.rb
app/entities/lcms/engine/curriculum_map.rb
app/interactors/lcms/engine/explore_curriculum_interactor.rb
app/models/lcms/engine/resource.rb
app/presenters/lcms/engine/curriculum_presenter.rb
app/views/lcms/engine/admin/resources/_fields.html.erb
lib/lcms/engine/test/resource_helpers.rb
lib/lt/lcms/metadata/context.rb

Also, wraps all the calls to `Lcms::Engine::Resource::HIERARCHY` to the method to allow altering the hierarchy from inside the host application.

Allows create resources of type `subject` with lesson import

---

Gemfile
lcms-engine.gemspec

The [vulnerabality](https://github.com/learningtapestry/lcms-engine/network/alert/lcms-engine.gemspec/rubyzip/closed)

Upgrade `rubyzip` gem to avoid security vulnerabilities

---

app/javascript/components/admin/ImportStatus.jsx
app/javascript/components/admin/MultiSelectedOperation.jsx
app/views/lcms/engine/admin/batch_reimports/import.html.erb
app/views/lcms/engine/admin/documents/import.html.erb
app/views/lcms/engine/admin/materials/import.html.erb
lib/doc_template/objects/base_metadata.rb
lib/doc_template/tables/base.rb
spec/lib/doc_template/objects/base_metadata_spec.rb
spec/lib/doc_template/tables/base_spec.rb

- Add new collect_and_render_tags
Introduce new `DocTemplate::Tables::Base#collect_and_render_tags` method which can be used to fetch a list of tags from a metadata table row, and correctly parse each of these tags.
- Add `Tables::Base#parse_in_context`
Used when we need to parse the content and render tags in the context environment
- Add `BaseMetadata.split_field`
Simple field splitter with a specified separator

Base metadata refactoring

---

app/controllers/lcms/engine/admin/batch_reimports_controller.rb
app/controllers/lcms/engine/admin/documents_controller.rb
app/controllers/lcms/engine/admin/materials_controller.rb
lib/doc_template.rb

Query objects should be defined in `config/lcms.yml` file
```yaml
queries:
document: 'AdminDocumentsQuery'
```

Allow customize AdminQuery objects

---

app/controllers/lcms/engine/admin/batch_reimports_controller.rb
app/views/lcms/engine/admin/documents/index.html.erb
lib/lt/lcms/metadata/context.rb

- When creating `Resource` it stores metadata for the current level only
- Minor refactoring
- Allows to override links to lessons after batch reimport
Need to specify in `lcms-admin.yml`:
```yaml
batch_reimports:
view_links:
- '/redirect-to-lesson/:id'
```

Fix metadata creation

---

lcms-engine.gemspec

To address the list of vulnerabilities https://weblog.rubyonrails.org/2019/3/13/Rails-4-2-5-1-5-1-6-2-have-been-released

Rails upgrade to 4.2.11.1

---

CHANGELOG.md
lib/doc_template/tags/base_tag.rb
spec/lib/doc_template/tags/base_tag_spec.rb

Occurs when tag has content with a word matching tag's name and complex styling:
> <p style='padding:0;font-size:11pt;font-family:\"Arial\";line-height:1.5;text-align:left'><span style='vertical-align:baseline;font-size:11pt;font-family:\"Cabin\";'>[image:OP.PT.L13.014, 50, Esta imagen muestra ruedas de carretas que han sido enterradas por la tierra movida por el viento durante una tormenta de polvo.] Los Estados Unidos tienen una historia trágica con sedimentos en movimiento por el viento. Durante la década de 1930, gran parte de los Estados Unidos estaba pasando por una sequía. La falta de agua hizo que el suelo se volviera seco, suelto y polvoriento. La sequía hizo que el suelo se aflojara, ya que había poca agua en la capa superior del suelo, arena y arcilla para mantenerla unida. El …

Fix parse loop when content of the tag  contains tag name

---

CHANGELOG.md
app/controllers/lcms/engine/admin/admin_controller.rb
spec/controllers/admin/admin_controller_spec.rb
spec/dummy/config/lcms-admin.yml
spec/dummy/config/routes.rb

Fix behavior when preview link is broken for `Document` and `Material` objects inside Admin panel.

Fix preview path on admin panel index

---

app/services/lcms/engine/html_sanitizer.rb
spec/services/html_sanitizer_spec.rb

Lcms::Engine::HtmlSanitizer.strip_content now correctly strips the empty elements. Before the fix general text elements were ignored by default.
Now stripping content like
```html
<p></p>
{{inset_11e85cccf407299a81ef}}
<p></p>
<h3 style="text-align:left;">
<span style="font-style:italic">In place of a semicolon</span><span>: The use of an em dash here is to create overwhelming emphasis or pause to influence shock and awe in your readers. </span>
</h3>
<p></p>
{{inset_392e9effbf47d0988b8c}}
<p></p>
```
will produce
```html
{{inset_11e85cccf407299a81ef}}
<p></p>
<h3 style="text-align:left;">
<span style="font-style:italic">In place of a semicolon</span><span>: The use of an em dash here is to create overwhelming emphasis or pause to influence shock and awe in your readers. </span>
</h3> …
```

Take TEXT elements into consideration while stripping content

---

yarn.lock

Address the following security issues:
- [serialize-javascript](https://github.com/learningtapestry/lcms-engine/network/alert/yarn.lock/serialize-javascript/closed)
- dot-prop

Bump vulnerable NodeJS packages

---

app/controllers/lcms/engine/admin/documents_controller.rb
app/forms/lcms/engine/document_form.rb
app/forms/lcms/engine/material_form.rb
app/javascript/components/admin/ImportStatus.jsx
app/jobs/lcms/engine/document_parse_job.rb
app/services/lcms/engine/document_build_service.rb
app/services/lcms/engine/material_build_service.rb
config/locales/admin/en.yml
lib/doc_template/tables/base.rb
lib/lt/lcms/metadata/base_service.rb
lib/lt/lcms/metadata/service.rb
spec/controllers/admin/documents_controller_spec.rb
spec/forms/document_form_spec.rb

Non-critical errors occurred during document or material metadata parsing now can be fetched during import process. In case when import process is running using ActiveJob workers, non-critical warnings can be fetched from Redis with general job results.

Capture errors during metadata parsing

---

Gemfile.lock
app/views/lcms/engine/admin/materials/index.html.erb
docker-compose.yml
lib/lcms/engine/engine.rb

Update usage of external decorators
- Also updates mimemagic gem
- Since Rails 6 introduced zeitwerk autoloader we need to review and change the way host application decorates engine's objects.
Consider the host application is named `MyApp`, then to decorate lcms-engine's objects the following should be done.
```ruby
module MyApp
  module Lcms
    module Engine
      module UserDecorator
        def self.prepended(base)
          # Any scope or possible class methods
          base.before_validation :some_method
        end
        def some_other_method
          true
        end
      end
    end
  end
end
::Lcms::Engine::User.prepend(MyApp::Lcms::Engine::UserDecorator)
```

Update usage of external decorators

---

Gemfile.lock
lcms-engine.gemspec
yarn.lock

- bump nokogiri gem ([issue](https://github.com/learningtapestry/lcms-engine/security/dependabot/Gemfile.lock/nokogiri/closed))
- bump postcss-svgo NodeJS package([issue](https://github.com/learningtapestry/lcms-engine/security/dependabot/yarn.lock/is-svg/closed))
- bump y18n NodeJS package([issue](https://github.com/learningtapestry/lcms-engine/security/dependabot/yarn.lock/y18n/closed))
- yarn upgrade to update other NodeJs packages

Security Updates (gems and NodeJS packages)

---

CHANGELOG.md
app/controllers/lcms/engine/admin/documents_controller.rb
app/controllers/lcms/engine/admin/materials_controller.rb
app/views/lcms/engine/admin/documents/new.html.erb
app/views/lcms/engine/admin/materials/new.html.erb
config/locales/ui/en.yml
spec/controllers/admin/documents_controller_spec.rb
spec/controllers/admin/materials_controller_spec.rb
spec/features/admin/materials/add_material_spec.rb

Refs #117
Add special checkbox (checked by default) to import document/material using ActiveJob.
The same functionality for Rails 6 has been added with #184

(#117) Import single document/material via delayed job

---

CHANGELOG.md
app/services/lcms/engine/s3_service.rb
spec/services/s3_service_spec.rb

Now one can pass a hash with options for the target S3 object. The list of options can be found in the description of `Aws::S3::Object#put` method.

Allow S3Service to upload with options

---

app/controllers/lcms/engine/admin/admin_controller.rb

Occurred when non-admin user tried to access the Admin panel. Redirection didn't work as expected.

Fix "undefined method `dynamic_path'"

---

app/presenters/lcms/engine/curriculum_presenter.rb
app/views/lcms/engine/admin/resources/index.html.erb

Curriculum Editor: fix the error when resource doesn't have _short_title_ value.

Fixes link to edit the resource

---

app/services/lcms/engine/google/script_service.rb

In case of an error log the ID of the Google Document which failed to be post-processed.

Update Google ScriptService

---

app/controllers/lcms/engine/welcome_controller.rb
config/routes.rb
docs/env-variables.md
docs/google-cloud-platform-setup.md
lib/tasks/google.rake
spec/controllers/admin/welcome_controller_spec.rb
spec/controllers/welcome_controller_spec.rb
spec/dummy/config/routes.rb

1. Update `google:setup_auth` rake task
Now task conforms with new OAuth application type (now it is Web Application). Also it allows to re-request auth token in case there is already one.
2.Introduce new `/oauth2callback` endpoint.
Accept a request to this endpoint only from `https://accounts.google.com/` referer.

Remove OOB flow in Google CLI credentials

---

Dockerfile
README.md
lcms-engine.gemspec

1. Bump ruby to 2.7.7
2. Add an instruction to build multi-arch Docker image.

Ruby v2.7.7 upgrade

---

CHANGELOG.md
app/controllers/concerns/lcms/engine/queryable.rb
app/controllers/lcms/engine/admin/batch_reimports_controller.rb
app/controllers/lcms/engine/admin/documents_controller.rb
app/controllers/lcms/engine/admin/materials_controller.rb
app/controllers/lcms/engine/admin/standards_controller.rb
app/controllers/lcms/engine/admin/users_controller.rb
app/queries/lcms/engine/admin_documents_query.rb
app/queries/lcms/engine/base_query.rb
app/views/lcms/engine/admin/batch_reimports/_search_form.html.erb

Possibly can break the inherited controllers. Apply changes carefully.
Unified query handling by extracting common query logic into `Lcms::Engine::Queryable` concern. Updated controllers and views to use the new concern for setting query parameters and constructing query structs, improving code maintainability and reducing redundancy.
This allows us to get rid of OpenStruct usage completely.

[BREAKING] Refactor query handling in admin controllers
